Internal: Internal1.o Internal2.o
	g++ -o Internal Internal1.o Internal2.o

Internal1.o: Internal1.cpp
	g++ -c Internal1.cpp

Internal2.o: Internal2.cpp
	g++ -c Internal2.cpp

Extern: Extern1.o Extern2.o
	g++ -o Extern Extern1.o Extern2.o

Extern1.o: Extern1.cpp
	g++ -c Extern1.cpp

Extern2.o: Extern2.cpp
	g++ -c Extern2.cpp
